import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
let chromium;
try { ({ chromium } = require('playwright')); } catch { ({ chromium } = require('/opt/node22/lib/node_modules/playwright')); }
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.setDefaultTimeout(120000);
const errors = [];
page.on('pageerror', (e) => errors.push(e.message + ' ' + e.stack));
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
await page.mouse.move(640, 360);
await page.goto('http://localhost:8080/index.html');
await page.waitForTimeout(1500);
const click = async (t) => { await page.getByText(t, { exact: false }).first().click(); await page.waitForTimeout(350); };
const out = {};
// quick match setup screen
await click('Quick Match');
await page.selectOption('#q-home', 'mancity');
await page.selectOption('#q-away', 'realmadrid');
await page.selectOption('#q-role', 'W');
await page.screenshot({ path: 'tests/out/ui_quick.png' });
await click('Kick Off');
await page.mouse.click(640, 360);
await page.waitForTimeout(600);
out.quickVenue = await page.evaluate(() => window.__ft.session.cfg.venue);
out.humanRole = await page.evaluate(() => window.__ft.session.human.role);
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
await click('Settings');
await page.click('[data-key="quality"] [data-v="low"]');
await page.click('[data-key="bob"] [data-v="false"]');
await page.locator('#s-fov').fill('100');
await page.screenshot({ path: 'tests/out/ui_settings.png' });
await click('Done');
out.settings = await page.evaluate(() => JSON.parse(localStorage.getItem('firsttouch.settings.v1')));
await click('Visual Style');
await page.waitForTimeout(500);
await page.locator('.preview[data-s="neo"]').click();
await page.waitForTimeout(300);
out.style = await page.evaluate(() => [window.__ft.style, localStorage.getItem('firsttouch.style')]);
await click('Back');
await click('Exit to Main Menu');
await page.waitForTimeout(400);
// training menu
await click('Training');
await page.screenshot({ path: 'tests/out/ui_training.png' });
await page.locator('[data-act="go"][data-k="finishing"]').click();
await page.waitForTimeout(400);
out.drill = await page.evaluate(() => window.__ft.session && window.__ft.session.cfg.mode);
await page.mouse.click(640, 360);
await page.waitForTimeout(300);
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
await click('Exit to Training');
await click('Back');
// career with a forced window + upgrade points
await click('New Career');
await click('Sign your first contract');
await page.evaluate(async () => {
  const c = window.__ft.store.career;
  c.player.points = 2;
  c.player.reputation = 30;
  c.form = [7.8, 7.6, 7.9, 7.5, 8.0];
  c.appsAtClub = 3;
  for (let i = 0; i < 5; i++) c.matchLog.push({ season: 1, round: 1, rating: 7.8, goals: 1, assists: 1, passCmp: 10, passAtt: 12, tackles: 1, interceptions: 1, keyPasses: 1, shotsOn: 2 });
  c.season.round = 4;
  const { openWindow } = window.__ftCareer || {};
  window.__ft.screens.hub();
});
await page.locator('[data-act="up"][data-k="finishing"]').click();
await page.waitForTimeout(300);
out.afterUpgrade = await page.evaluate(() => [window.__ft.store.career.player.attrs.finishing, window.__ft.store.career.player.points]);
await page.screenshot({ path: 'tests/out/ui_hub_upgrade.png' });
console.log(JSON.stringify(out, null, 1));
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'no errors');
await browser.close();
